// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IBlockFields {
  /** Heading */
  heading: string;

  /** Image */
  image: Asset;
}

export interface IBlock extends Entry<IBlockFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'block';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IGalleryFields {
  /** Name */
  name?: string | undefined;

  /** Images */
  images?: Asset[] | undefined;
}

export interface IGallery extends Entry<IGalleryFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'gallery';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IPageFields {
  /** Name */
  name?: string | undefined;

  /** Slug */
  slug?: string | undefined;

  /** Block */
  block?: (IGallery | IBlock | IText)[] | undefined;
}

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'page';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ITextFields {
  /** Heading */
  heading?: string | undefined;

  /** Text */
  text?: Document | undefined;
}

export interface IText extends Entry<ITextFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'text';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'block' | 'gallery' | 'page' | 'text';

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
